server:
  port: 8080
  servlet:
    context-path: /

#
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:exercise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

#
logging:
  level:
    root: ERROR
    com.paf.exercise: DEBUG