CREATE TABLE IF NOT EXISTS TOURNAMENT(
  id BIGINT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  reward_amount VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLAYER(
  id BIGINT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TOURNAMENT_PLAYER(
  id BIGINT PRIMARY KEY NOT NULL,
  tournament_id BIGINT NOT NULL,
  player_id BIGINT NOT NULL,
  FOREIGN KEY (tournament_id) REFERENCES TOURNAMENT(id),
  FOREIGN KEY (player_id) REFERENCES PLAYER(id)
);

